### ISSUE TITLE
vbpp-algorithm option - onedimensional

### ISSUE THREAD

**Issue by lafar6502** [fontanf/packingsolver#10]
Hi Florian
First of all, thanks for wonderful job with compilation, now packingsolver builds on Windows 'as is' without any problems (the master branch).
I've been checking some stuff with the newest build but have encountered some behavior that's not clear for me
This is built with clp enabled (--define clp=true)

Attached is an archive with bins, items and 4 test files.
The difference between tests is in vbpp-algorithm option
First test (test0.cmd) doesn't specify vbpp-algorithm at all. This one runs correctly and gives a solution 
Next tests are with different vbpp-algorithm
test1: --objective variable-sized-bin-packing --vbpp-algorithm sequential-value-correction
test2: --objective variable-sized-bin-packing --vbpp-algorithm column-generation
test3: --objective variable-sized-bin-packing --vbpp-algorithm dichotomic-search

these 3 tests don't produce any results - no solution, nothing is printed on stdout/stderr
[tmpopt.zip](https://github.com/fontanf/packingsolver/files/14894481/tmpopt.zip)

BTW I used your one dimensional solver to make a cut optimizer for a manufacturer of venetian blinds/roller blinds and it's already used in production. I think it's working very well - makes cutting plans for saw operators. Started slowly as it wasnt obvious if the calculation is useful for production but with time they started to trust the results and found many cases where it's really helpful (i think they adjusted the way of working to better match the optimized/planned approach). We're still developing this but at this stage i think it's there to stay for good. Thanks again for this project. Is there a way to buy you a coffee?

(edit) i looked at the source files and couldn't find any reference to vbpp-algorithm in the onedimensional source folder. Maybe this option is not applicable to one dimensional?

**Comment by fontanf** [comment]
Hi,

In the current master branch, I replaced the `--vbpp-algorithm` option by the following options:
* `--use-tree-search`
* `--use-sequential-single-knapsack`
* `--use-sequential-value-correction`
* `--use-column-generation`
* `--use-dichotomic-search`

I had not added these options for onedimensional problems. I just did it. You'll need to pull if you want to use them.

If all of them have value 0, which is their default value, then the solver chooses automatically what to do. If multiple algorithms are set to 1, then they are executed in parallel.

No need to buy me a coffee. But I'm interested in datasets for one-dimensional problems. Do not hesitate to provide some if you can. I would be able to use them to test the code and benchmark future developments. If later you need some more complex features, we might discuss about some commercial collaboration

**Comment by lafar6502** [comment]
Hi,

I have checked the most recent build with these new command line options, but it looks there's still something wrong.
If i use any of --use-sequential-value-correction, --use-column-generation, --use-dichotomic-search
there's no output, nothing on console, no solution created.
Attached test case
[test_0407_1.zip](https://github.com/fontanf/packingsolver/files/14896217/test_0407_1.zip)
About more complex features and commercial collaboration - glad that there is such an option but i can't tell if or when we'll need custom/more advanced features. I'll be trying to find some more use cases for optimization.
But if you happen to be building or renovating a house and would need some sun shading stuff with a nice discount, let me know.

**Comment by fontanf** [comment]
These options take value 0 or 1:

```
./bazel-bin/packingsolver/onedimensional/main  --verbosity-level 2  --objective variable-sized-bin-packing  --items data/onedimensional/users/2024-04-07   --certificate solution.csv  --use-sequential-value-correction 1
```
```
=================================
          PackingSolver          
=================================

Problem type
------------
OneDimensional

Instance
--------
Objective:             VariableSizedBinPacking
Number of item types:  4
Number of items:       7
Number of bin types:   2
Number of bins:        8000

    Bin type      Length    Max wght        Cost      Copies  Copies min
    --------      ------    --------        ----      ------  ----------
           0        3000         inf        3000        3000           0
           1        7000         inf        7000        5000           0

   Item type      Length      Weight   MaxWgtAft     MaxStck      Profit      Copies
   ---------      ------      ------   ---------     -------      ------      ------
           0         290           0         inf       32767         290           1
           1        1496           0         inf       32767        1496           2
           2        2751           0         inf       32767        2751           2
           3        3351           0         inf       32767        3351           2

        Time          Cost  # bins  Full waste (%)                         Comment
        ----          ----  ------  --------------                         -------
       0.002         19000       5           18.49                        SVC it 0
^C
Final statistics
----------------
Time (s):  5.83069

Solution
--------
Number of items:  7 / 7 (100%)
Item length:      15486 / 15486 (100%)
Item profit:      15486 / 15486 (100%)
Number of bins:   5 / 8000 (0.0625%)
Bin length:       19000 / 44000000 (0.0431818%)
Bin cost:         19000
Waste:            804
Waste (%):        4.93554
Full waste:       3514
Full waste (%):   18.4947

         Bin        Type      Copies      Length      Weight     # items
         ---        ----      ------      ------      ------     -------
           0           0           1        2997           0           2
           1           1           1        6707           0           2
           2           0           2        2751           0           1
           3           0           1         290           0           1
```

**Comment by lafar6502** [comment]
Yep, thanks, just discovered this at the very moment you wrote
All algorigthms worked for my test case and generated results, so now we can experiment with which approach gives the best results.

**Comment by fontanf** [comment]
Great. If you have 8 threads on your machine, I recommend using the default configuration. It runs in parallel the column generation algorithm + one of the other algorithms depending on the characteristics of the problem. If you have more threads, you can enable all algorithms

**Comment by fontanf** [comment]
I tried. If you find a problem for which the default configuration is not the one returning the best solution, you can send it to me
