### ISSUE TITLE
Negative item_type.group_id causes crash

### ISSUE THREAD

**Issue by bbeaulant** [fontanf/packingsolver#111]
The ItemType `group_id` property is used directly without checking if it's a positive value.

But the following line failed with negative value :

https://github.com/fontanf/packingsolver/blob/e5ed4ca362ef3835733221fda2d8a156166b47bb/src/rectangle/instance_builder.cpp#L630

**Comment by fontanf** [comment]
Hi,

Thank you for reporting.

If should be fixed in 9586fb44f161c2d3706a2606e94611186e98d959
