### ISSUE TITLE
Trapezoid not found causes crash

### ISSUE THREAD

**Issue by bbeaulant** [fontanf/packingsolver#112]
An invalid shape with holes outside its outline may cause the `find_trapezoid_containing_vertex` function to return a `open_trapezoid_pos` of -1. Which crashes the program with invalid vector index. It might be a interesting to throw an exception.

https://github.com/fontanf/packingsolver/blob/e5ed4ca362ef3835733221fda2d8a156166b47bb/src/irregular/polygon_trapezoidation.cpp#L304

**Comment by fontanf** [comment]
Hi,

Thank you for reporting.

It should be fixed in 0600c9a82ccc74cf1ef592c0f3237cb1ec8f0d14
