### ISSUE TITLE
Irregular solution areas value types : Area vs AreaDbl

### ISSUE THREAD

**Issue by bbeaulant** [fontanf/packingsolver#113]
These both area values are truncated to `Area` even if [BinType](https://github.com/fontanf/packingsolver/blob/e5ed4ca362ef3835733221fda2d8a156166b47bb/include/packingsolver/irregular/instance.hpp#L310) and [ItemType](https://github.com/fontanf/packingsolver/blob/e5ed4ca362ef3835733221fda2d8a156166b47bb/include/packingsolver/irregular/instance.hpp#L364) areas are `AreaDbl`. Is this data loss necessary?

https://github.com/fontanf/packingsolver/blob/e5ed4ca362ef3835733221fda2d8a156166b47bb/include/packingsolver/irregular/solution.hpp#L192

https://github.com/fontanf/packingsolver/blob/e5ed4ca362ef3835733221fda2d8a156166b47bb/include/packingsolver/irregular/solution.hpp#L195

**Comment by fontanf** [comment]
Hi,

Thank you for reporting.

It should be fixed in 65069a0bd8ef2a5b5d49637450adf264ba051183
