### ISSUE TITLE
Possible typo in RectangleGuillotine instance write method

### ISSUE THREAD

**Issue by bbeaulant** [fontanf/packingsolver#117]
Hello,

Maybe the - should be replaced by _ in the following line : 

https://github.com/fontanf/packingsolver/blob/0600c9a82ccc74cf1ef592c0f3237cb1ec8f0d14/src/rectangleguillotine/instance.cpp#L312

**Comment by fontanf** [comment]
Hi,

Thank you for reporting.

It's fixed in 6b70bff354acb9826038b7660b507318365543e6
