### ISSUE TITLE
How to complie the released version of source code and use  irregular solver

### ISSUE THREAD

**Issue by xinzhou0714** [fontanf/packingsolver#119]
Hallo， 
I am trying to use your packingsolver program, but in your released version "packingsolver-1.1.0.tar.gz" does not exist a CMakeLists.txt file, can your give me some instructions, so that i can use cmake to compile the code and get the executable file.

And I want also to know how to define some irregular polygons as input for programm.

Thank you for your help!

Best regards,
Xin Zhou

**Comment by fontanf** [comment]
Hi,

The last release is quite old. It doesn't contain the irregular solver and doesn't compile with CMake. I recommend you tu use the master version instead.

There is no documentation for the irregular solver yet. Look at the input data from the repository as examples: 
* https://github.com/fontanf/packingsolver/tree/master/data/irregular
* https://github.com/fontanf/packingsolver/blob/master/data/irregular/opencutlist/knight_armor.json

**Comment by xinzhou0714** [comment]
Thanks for your answer and the result of solver looks really nice !

**Comment by fontanf** [comment]
No problem. Do not hesitate if you have other questions
