### ISSUE TITLE
Onedimensional - incorrect solution found

### ISSUE THREAD

**Issue by lafar6502** [fontanf/packingsolver#13]
Hi, i have another problematic case
```

BINS:
ID,X,COST,COPIES
0,6950,6950,8
1,7000,3500,2

ITEMS:
ID,X,COPIES,NESTING_LENGTH
0,2408,8,-4

RESULT:
TYPE,ID,COPIES,BIN,X,LX
BIN,1,2,0,0,7000
ITEM,0,2,0,0,2408
ITEM,0,2,0,2412,2408
BIN,1,1,1,0,7000
ITEM,0,1,1,0,2408
ITEM,0,1,1,2412,2408
BIN,0,1,2,0,6950
ITEM,0,1,2,0,2408
ITEM,0,1,2,2412,2408
```

The problem here is that the solution is incorrect - we have 2 bins of type 1 available (and 8 bins of type 0)
But the solution requires 3 bins of type 1 and 1 bin of type 0

cmdline:
`main.exe --objective variable-sized-bin-packing  --items items1.csv --bins bins1.csv -c solution1.csv -t 5
`
[test1.zip](https://github.com/fontanf/packingsolver/files/14919087/test1.zip)

And here is the output from old build (end of 2023) - this one is correct:

```
TYPE,ID,COPIES,BIN,X,LX
BIN,0,2,0,0,6950
ITEM,0,2,0,0,2408
ITEM,0,2,0,2412,2408
BIN,1,2,1,0,7000
ITEM,0,2,1,0,2408
ITEM,0,2,1,2412,2408
```

**Comment by fontanf** [comment]
Hi,

Thanks for reporting. It should now be fixed in the latest master branch

**Comment by lafar6502** [comment]
Thank you, now it calculated correctly.
