### ISSUE TITLE
Extra rectangles returned in solution file.

### ISSUE THREAD

**Issue by riccardodivirgilio** [fontanf/packingsolver#2]
Hi, I'm trying to use this library however I'm running into a problem.

I created 2 files, bins and rects that I'm feeding to the program.

[solver-b.csv](https://github.com/fontanf/packingsolver/files/11077067/solver-b.csv)
[solver-r.csv](https://github.com/fontanf/packingsolver/files/11077068/solver-r.csv)
[solver-s.csv](https://github.com/fontanf/packingsolver/files/11077069/solver-s.csv)

The result output is returning some extra rects that are not in the list I gave to the program. specifically the first 3 lines of the solution are not rectangles I'm providing:

```
0,0,0,0,1000000,700000,-2,0,
0,1,0,0,1000000,636000,-2,1,0
0,2,0,0,102000,636000,-2,2,1
```

The first one seems to be the outer rect, with a PARENT col that is set to null, but the second 2 rects are identical to all other rects and there is no simple way of removing them without manually checking if they are one of the rect I provided.

Is there a way to easily discard all rects in the solution file that is not part of the solution?

Thanks

**Comment by riccardodivirgilio** [comment]
it looks like I can filter all rectangles with TYPE >= 0 in order to get them? Is there a list of types somewhere? thanks

**Comment by fontanf** [comment]
Hi,

In the CSV output file, the items correspond to lines with a positive value in the `TYPE` column. The bins to the lines with a 0 in the `CUT` column. The other lines correspond to the intermediate subplates obtained during cutting

**Comment by riccardodivirgilio** [comment]
thanks! consider mentioning this detail in the readme.
