### ISSUE TITLE
Failed to build on "arm64" architecture

### ISSUE THREAD

**Issue by bbeaulant** [fontanf/packingsolver#31]
Hi @fontanf ,

First, thank you for sharing your work.

I'm trying to build `packingsolder` project on Apple M1 computer and it failed to because several dependencies are not available for arm64 architecture.

Is this a problem that can be worked around?

```
ld: warning: ignoring file 'packingsolver/build/_deps/mathoptsolverscmake-build/extern/Clp-prefix/src/Clp/lib/libOsiClp.1.14.8.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file 'packingsolver/build/_deps/mathoptsolverscmake-build/extern/Clp-prefix/src/Clp/lib/libClp.1.14.8.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file 'packingsolver/build/_deps/mathoptsolverscmake-build/extern/Clp-prefix/src/Clp/lib/libOsi.0.0.0.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file 'packingsolver/build/_deps/mathoptsolverscmake-build/extern/Clp-prefix/src/Clp/lib/libOsiCommonTests.0.0.0.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file 'packingsolver/build/_deps/mathoptsolverscmake-build/extern/Clp-prefix/src/Clp/lib/libCoinUtils.0.0.0.dylib': found architecture 'x86_64', required architecture 'arm64'
```

**Comment by fontanf** [comment]
Hi,

Indeed, CLP doesn't provide binaries for Mac ARM.

The two workarounds I see:
* If you don't need the column generation algorithm, there should be a way not depend on CLP
* If you find another way to install CLP, we might tell the build system to find it there

**Comment by bbeaulant** [comment]
> CLP doesn't provide binaries for Mac ARM.

Zut :(

> If you find another way to install CLP, we might tell the build system to find it there

On Mac OS, CLP seams to be installable through [Homebrew](https://brew.sh/) ([ref](https://github.com/coin-or/Clp?tab=readme-ov-file#binaries)). But I'am not sur it could be the easiest way to automate it.

**Comment by fontanf** [comment]
Indeed, using the homebrew version looks like a good solution. I'll try to make it work in the coming days (I'm not very familiar with Mac OS)

**Comment by bbeaulant** [comment]
Hi,

I don't know if to can help you, but after brewing CLP, the following message appear.

```
clp is keg-only, which means it was not symlinked into /opt/homebrew,
because conflicts with formula in core.

If you need to have clp first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/clp/bin:$PATH"' >> ~/.zshrc

For compilers to find clp you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/clp/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/clp/include"

For pkg-config to find clp you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/clp/lib/pkgconfig"
```

**Comment by fontanf** [comment]
It helped. It should be working with the latest master now. Let me know if it's not the case

**Comment by bbeaulant** [comment]
Thanks, but it blocks on the following error now : 

```
[...]
[ 52%] Built target KnapsackSolver_knapsack_dynamic_programming_primal_dual
In file included from packingsolver/build/_deps/columngenerationsolver-src/src/algorithms/column_generation.cpp:1:
In file included from packingsolver/build/_deps/columngenerationsolver-src/include/columngenerationsolver/algorithms/column_generation.hpp:3:
packingsolver/build/_deps/columngenerationsolver-src/include/columngenerationsolver/linear_programming_solver.hpp:6:10: fatal error: 'coin/ClpModel.hpp' file not found
#include <coin/ClpModel.hpp>
```

Maybe I forgot to do something?

**Comment by fontanf** [comment]
In the Github runners, the prefix directory of Homebrew is `/opt/homebrew`, such that there is a directory `/opt/homebrew/include/clp`. Your prefix is probably different. If I've done things correctly, you should be able to use a custom Homebrew prefix by setting the corresponding variable in the first cmake command:

```sh
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DMATHOPTSOLVERSCMAKE_HOMEBREW_PREFIX="/opt/homebrew`
```

**Comment by bbeaulant** [comment]
Ok. I've got it !

I'v installed `brew install coin-or-tools/coinor/clp` (from [official repo](https://github.com/coin-or/Clp?tab=readme-ov-file#binaries)) and not common `brew install clp`

After using `brew install clp`, It compile, thank you 👍

**Comment by fontanf** [comment]
Thank you for the update. I'm glad it works. I don't know what's the difference between the two commands. The second one works in the pipelines, so I'm going to keep it for now, but I keep the other one in mind in case someone else encounters the same issue
