### ISSUE TITLE
Examples/documentation for onedimensional

### ISSUE THREAD

**Issue by lafar6502** [fontanf/packingsolver#4]
Hi, 
First of all, thanks for developing this project. I'm looking for a simple tool to optimize cutting of metal profiles in small production company and hopefully i have just found it.
The only thing missing is documentation or examples - i don't know how to prepare the input data and what is the meaning of all configuration options in the onedimensional solver (this is for 1d cutting only).
Do you have any examples for 1d, or more detailed description of its options?

The problem to solve: the company is producing various stuff from aluminium profiles that need to be cut to a specified length.
The raw profiles are available in several lengths, for example 3 meters, 7 meters and 10 meters.
And the saw operator is supposed to cut a number of pieces of various lengths. They need a tool that will tell the operator which raw material lengths to use and how to cut them in order to get minimum waste. 
Would also be nice if we could address the cut width somehow - the metal saw takes few mm of material on each cut so it needs to be accounted for. Of course we can increase the length of each piece by the saw width, but there are some edge conditions where this is not applicable, like when the piece size is almost exact length of the raw material. Does the program have any way to handle the cut width?

**Comment by fontanf** [comment]
Hi,

Enclosed an example of input files:

[example_1_bins.csv](https://github.com/fontanf/packingsolver/files/12136898/example_1_bins.csv)
[example_1_items.csv](https://github.com/fontanf/packingsolver/files/12136899/example_1_items.csv)

Then, here is how to call the solver:
```
./bazel-bin/packingsolver/onedimensional/main  --verbosity-level 2 --objective variable-sized-bin-packing   --vbpp-algorithm sequential-value-correction  --items data/onedimensional/examples/example_1_items.csv --bins data/onedimensional/examples/example_1_bins.csv  -c solution.csv -t 1
```
```
===================================
           PackingSolver           
===================================

Problem type
------------
onedimensional

Instance
--------
Objective:                VariableSizedBinPacking
Number of item types:     10
Number of items:          3274
Number of bin types:      3
Number of bins:           30000

    Bin type      Length    Max wght        Cost      Copies  Copies min
    --------      ------    --------        ----      ------  ----------
           0        3000         inf        3000       10000           0
           1        7000         inf        8008       10000           0
           2       10000         inf       10000       10000           0

   Item type      Length      Weight   MaxWgtAft     MaxStck      Profit      Copies
   ---------      ------      ------   ---------     -------      ------      ------
           0        9809           0         inf       32767        9809         236
           1         739           0         inf       32767         739           4
           2        4624           0         inf       32767        4624         241
           3        3589           0         inf       32767        3589         884
           4        8369           0         inf       32767        8369          48
           5        3236           0         inf       32767        3236         348
           6        3470           0         inf       32767        3470         302
           7         732           0         inf       32767         732         299
           8         365           0         inf       32767         365         613
           9        2056           0         inf       32767        2056         299

Algorithm
---------
Sequential Value Correction

        Time          Cost  # bins  Full waste (%)                         Comment
        ----          ----  ------  --------------                         -------
       0.027   1.16263e+07    1169            0.00                     iteration 0
       0.054   1.16202e+07    1168            0.00                     iteration 1
       0.078   1.16182e+07    1168            0.00                     iteration 2
       0.103     1.138e+07    1138            0.00                     iteration 3
       0.131    1.1334e+07    1134            0.00                     iteration 4
       0.214   1.13101e+07    1134            0.00                     iteration 7
       0.497   1.09862e+07    1104            0.00                    iteration 16
       0.529   1.07753e+07    1086            0.00                    iteration 17
       0.750   1.07464e+07    1085            0.00                    iteration 24

Final statistics
----------------
Cost:              1.07464e+07
Number of bins:    1085
Full waste (%):    0
Time:              1.00001

         BIN        TYPE      COPIES      LENGTH      WEIGHT     # ITEMS
         ---        ----      ------      ------      ------     -------
           0           2           1        9896           0           6
           1           2          48        9833           0           3
           2           2         120        9980           0           3
           3           2          20        9987           0           6
           4           2           1        9985           0           7
           5           2         299        9964           0           5
           6           2           1        9979           0          10
           7           2           1        9919           0           7
           8           2         174        9942           0           3
           9           2         236        9809           0           1
          10           1          51        6940           0           2
          11           2         132        7178           0           2
          12           1           1        3470           0           1
```

Note that for the kind of problems you mention, PackingSolver includes another algorithm that might work very well but requires to have a linear programming solver installed such as [CLP](https://github.com/coin-or/Clp) and then to compile PackingSolver with
```
bazel build --define clp=true -- //...
```

Then:
```
./bazel-bin/packingsolver/onedimensional/main  --verbosity-level 2 --objective variable-sized-bin-packing  --items data/onedimensional/examples/example_1_items.csv --bins data/onedimensional/examples/example_1_bins.csv  -c solution.csv -t 1
```
```
===================================
           PackingSolver           
===================================

Problem type
------------
onedimensional

Instance
--------
Objective:                VariableSizedBinPacking
Number of item types:     10
Number of items:          3274
Number of bin types:      3
Number of bins:           30000

    Bin type      Length    Max wght        Cost      Copies  Copies min
    --------      ------    --------        ----      ------  ----------
           0        3000         inf        3000       10000           0
           1        7000         inf        8008       10000           0
           2       10000         inf       10000       10000           0

   Item type      Length      Weight   MaxWgtAft     MaxStck      Profit      Copies
   ---------      ------      ------   ---------     -------      ------      ------
           0        9809           0         inf       32767        9809         236
           1         739           0         inf       32767         739           4
           2        4624           0         inf       32767        4624         241
           3        3589           0         inf       32767        3589         884
           4        8369           0         inf       32767        8369          48
           5        3236           0         inf       32767        3236         348
           6        3470           0         inf       32767        3470         302
           7         732           0         inf       32767         732         299
           8         365           0         inf       32767         365         613
           9        2056           0         inf       32767        2056         299

Algorithm
---------
Column generation

        Time          Cost  # bins  Full waste (%)                         Comment
        ----          ----  ------  --------------                         -------
       0.069   1.07205e+07    1085            0.00                   discrepancy 0
       0.118   1.07185e+07    1085            0.00                   discrepancy 1

Final statistics
----------------
Cost:              1.07185e+07
Number of bins:    1085
Full waste (%):    0
Time:              1.08752

         BIN        TYPE      COPIES      LENGTH      WEIGHT     # ITEMS
         ---        ----      ------      ------      ------     -------
           0           1           1        6825           0           2
           1           2          81        7178           0           2
           2           2           1        8943           0           4
           3           2         120        9248           0           2
           4           2          61        9733           0           9
           5           2          92        9964           0           5
           6           2         207        9966           0           4
           7           2          46        9833           0           3
           8           1          64        6940           0           2
           9           2         173        9942           0           3
          10           2         236        9809           0           1
          11           2           2        9847           0           3
          12           1           1        6706           0           2
```


The file `solution.csv` contains the details of the solution is CSV format.

Do net hesitate to let me know if something is not clear.

The cut width feature is not included in the `onedimensional` problem. It doesn't seem difficult to integrate into the algorithm, but I won't have time to do it before a few weeks.

**Comment by lafar6502** [comment]
Ha, it worked, and i even understood the output. Very nice, thanks! Will be experimenting more with this in next days.
One little thing to remember: if the items csv file  includes an empty line at the end (an extra LF character) the program doesn't generate any response/message, just no output at all. 

I've been also chaotically going thru your other projects, and found other algorightms, including columngenerationsolver (that has Cutting Stock solving code and some examples for that), and knapsack solver. 
How are these related to packingsolver project? I mean, are these algorithms included in packingsolver/used by packingsolver, or are they separate tools for solving specific kinds of problems? 

BTW i also tried to compile columngenerationsolver (in Linux and Windows) and got some compilation errors in both cases. Probably something missing on my side, so i'm not putting details here - maybe i don't need to compile them at all if the same algorithms are part of packingsolver

**Comment by fontanf** [comment]
I just did a few fixes. Do not hesitate to pull the latest version.

Thanks for reporting the input file issue. I'll look at it.

The column generation algorithm of PackingSolver, which is actually the one I mentioned in my previous message, is implemented with my columngenerationsolver library. The subproblems are solved with tree search algorithms implemented with my treesearchsolver library, and not with my knapsacksolver library, since even if the subproblem is a knapsack problem, it includes additional features that require a dedicated algorithm. The knapsacksolver library is still used in some other algorithms of PackingSolver.

In addition to the column generation algorithm, PackingSolver includes two other algorithms for variable-sized bin packing that might work better than the column generation algorithm depending on the instance characteristics.

Do not hesitate to report the compilation issues you encounter.

**Comment by lafar6502** [comment]
OK so let's look at this compilation problem as I'm interested in comparing different algorithms.
(i'm taking the master branch), on Linux first (although the target platform would be Windows)
So i installed the CLP and tried to compile packingsolver this time with
`bazel build --define clp=true -- //...`
The error message i get is the following:

`
Starting local Bazel server and connecting to it...
ERROR: /home/rg/packingsolver/WORKSPACE:80:21: fetching new_local_repository rule //external:coinor: java.io.IOException: The repository's path is "/home/florian/Programmes/coinbrew/" (absolute: "/home/florian/Programmes/coinbrew") but this directory does not exist.
ERROR: /home/rg/packingsolver/packingsolver/algorithms/BUILD:21:11: //packingsolver/algorithms:algorithms depends on @coinor//:clp in repository @coinor which failed to fetch. no such package '@coinor//': The repository's path is "/home/florian/Programmes/coinbrew/" (absolute: "/home/florian/Programmes/coinbrew") but this directory does not exist.
ERROR: Analysis of target '//packingsolver/algorithms:algorithms' failed; build aborted: Analysis failed
INFO: Elapsed time: 4.176s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (43 packages loaded, 1904 targets configured)
    currently loading: @columngenerationsolver//columngenerationsolver ... (2 packages)
`

**Comment by fontanf** [comment]
Yes sorry, I forgot to mention that you need to update the WORKSPACE file and set the right location of CLP on your machine after the path attribute:

```
new_local_repository(
    name = "coinor",
    path = "/home/florian/Programmes/coinbrew/",
    build_file_content = """
```

**Comment by fontanf** [comment]
Actually, you can get a cut width using the "NESTING_HEIGHT" item property with negative values. It's not what it was meant for but it seems to work

```
ID,X,COPIES,NESTING_LENGTH
0,9809,236,-010
1,739,4,-100
2,4624,241,-100
3,3589,884,-100
4,8369,48,-100
5,3236,348,-100
6,3470,302,-100
7,732,299,-100
8,365,613,-100
9,2056,299,-100
```

**Comment by lafar6502** [comment]
Thanks Florain, fantastic! 

Also, i managed to compile packingsolver under Linux with CLP (just compiled, didnt test if it runs correctly).
Took CLP from the binary distributions page https://github.com/coin-or/Clp/releases
And although im using Ubuntu 22, had to take the version for ubuntu 20.04 with dynamic libraries, because they have only provided statically linked version for ubuntu 22.04. And it appears we need dynamic CLP libraries


Which brings me to Windows compilation :)
Installed the Windows clp binary for MSVC 17 from the same CLP release page.
It appears only statically linked version is provided for Windows, no dlls.
And the compilation attempt results in:
`
INFO: Analyzed 19 targets (1 packages loaded, 144 targets configured).
INFO: Found 19 targets...
ERROR: C:/devs/packingsolver/packingsolver/boxstacks/BUILD:37:10: Copying Execution Dynamic Library failed: missing input file '@coinor//:dist/lib/libClp.so'
ERROR: C:/devs/packingsolver/packingsolver/irregular/BUILD:36:10: Copying Execution Dynamic Library failed: missing input file '@coinor//:dist/lib/libClp.so'
ERROR: C:/devs/packingsolver/packingsolver/irregular/BUILD:36:10: Copying Execution Dynamic Library failed: 1 input file(s) do not exist
ERROR: C:/devs/packingsolver/packingsolver/boxstacks/BUILD:37:10: Copying Execution Dynamic Library failed: 1 input file(s) do not exist
ERROR: C:/devs/packingsolver/packingsolver/rectangle/BUILD:32:10: Copying Execution Dynamic Library failed: missing input file '@coinor//:dist/lib/libCoinUtils.so'
ERROR: C:/devs/packingsolver/packingsolver/rectangle/BUILD:32:10: Copying Execution Dynamic Library failed: missing input file '@coinor//:dist/lib/libClp.so'
ERROR: C:/devs/packingsolver/packingsolver/irregular/BUILD:36:10 Copying Execution Dynamic Library failed: 1 input file(s) do not exist
INFO: Elapsed time: 2.520s, Critical Path: 0.20s
INFO: 5 processes: 5 internal.
FAILED: Build did NOT complete successfully
`
So one problem is that the build script is looking for *.so libraries, which is not great because in Windows we need *.dll.
The other problem is that i don't have CLP build with dynamic libraries, only static ones (*.lib files).
Not sure if this is easily solvable, maybe some work around can be found (different library instead of CLP?)
But it's not a show stopper for me, just not possible to use columngeneratorsolver for now.

**Comment by fontanf** [comment]
It's possible to use static libraries with bazel. I think you just need to replace the .so files by the .lib ones in:

```
new_local_repository(
    name = "coinor",
    path = "/home/florian/Programmes/coinbrew/",
    build_file_content = """
cc_library(
    name = "osi",
    hdrs = glob(["dist/include/coin/Osi*.h*"], exclude_directories = 0),
    strip_include_prefix = "dist/include/coin/",
    visibility = ["//visibility:public"],
)
cc_library(
    name = "coinutils",
    hdrs = glob(["dist/include/coin/Coin*.h*"], exclude_directories = 0),
    strip_include_prefix = "dist/include/coin/",
    srcs = [
        "dist/lib/libCoinUtils.so",
    ],
    visibility = ["//visibility:public"],
)
cc_library(
    name = "clp",
    hdrs = glob(["dist/include/coin/Clp*.h*"], exclude_directories = 0),
    strip_include_prefix = "dist/include/coin",
    srcs = [
        "dist/lib/libClp.so",
    ],
    deps = [":coinutils", ":osi"],
    visibility = ["//visibility:public"],
)
""",
)
```

For example, for Cplex, it looks like this:

```
new_local_repository(
    name = "cplex",
    path = "C:/Program Files/IBM/ILOG/CPLEX_Studio129",
    build_file_content = """
cc_library(
    name = "concert",
    hdrs = glob(["concert/include/ilconcert/**/*.h"], exclude_directories = 0),
    strip_include_prefix = "concert/include/",
    srcs = [
        "concert/lib/x64_windows_vs2015/stat_mda/concert.lib",
        "concert/lib/x64_windows_vs2015/stat_mdd/concert.lib",
    ],
    linkopts = [
            "-lm",
            "-lpthread",
            "-ldl",
    ],
    visibility = ["//visibility:public"],
)
cc_library(
    name = "cplex",
    hdrs = glob(["cplex/include/ilcplex/*.h"]),
    strip_include_prefix = "cplex/include/",
    srcs = [
            "cplex/lib/x64_windows_vs2015/stat_mda/ilocplex.lib",
            "cplex/lib/x64_windows_vs2015/stat_mda/cplex1290.lib",
            "cplex/lib/x64_windows_vs2015/stat_mdd/ilocplex.lib",
            "cplex/lib/x64_windows_vs2015/stat_mdd/cplex1290.lib",
    ],
    deps = [":concert"],
    visibility = ["//visibility:public"],
)
cc_library(
    name = "cpoptimizer",
    hdrs = glob(["cpoptimizer/include/ilcp/*.h"]),
    strip_include_prefix = "cpoptimizer/include/",
    srcs = [
        "cpoptimizer/lib/x64_windows_vs2015/stat_mda/cp.lib",
        "cpoptimizer/lib/x64_windows_vs2015/stat_mdd/cp.lib",
    ],
    deps = [":cplex"],
    visibility = ["//visibility:public"],
)
""",
)
```

Unfortunately, I can't test the compilation with CLP on Windows right now

**Comment by lafar6502** [comment]
You're right, looks like we can specify .lib 
However, it didnt help - im getting just a long list of linking errors, version conflicts etc. Probably some library/compiler version incompatibilities between CLP build and my environment. Anyway, let's return to it if/when it's really necessary.
R

**Comment by lafar6502** [comment]
OK, spent some time on compilation for Windows and CLP and i think i have it. 
Below is a list of steps i have done, maybe it will be useful to someone struggling with compilation.

1. Downloaded CLP binary distribution for MSVC 17 from github releases page
2. Extracted clp archive to clp/dist next to my packingsolver sources (dist subfolder because WORKSPACE uses dist everywhere and i didn't want to change it)
3. adjusted the WORKSPACE file - fixed the CLP path reference and changed library names from .so to .lib
4. Made sure BAZEL_VC environment variable points to correct MSVC directory (this is for VS 2022)
5. added  --cxxopt=/MT build option (this is for selecting proper version of msvc standard libraries)

this is my build command line:
`
set BAZEL_VC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC
bazel build --define clp=true --cxxopt=/MT -- //...
`

and these are changes made in WORKSPACE file (git diff...)
`
diff --git a/WORKSPACE b/WORKSPACE
index 39824db6..2d83c470 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -79,7 +79,7 @@ local_repository(
 
 new_local_repository(
     name = "coinor",
-    path = "/home/florian/Programmes/coinbrew/",
+    path = "../clp",
     build_file_content = """
 cc_library(
     name = "osi",
@@ -92,7 +92,7 @@ cc_library(
     hdrs = glob(["dist/include/coin/Coin*.h*"], exclude_directories = 0),
     strip_include_prefix = "dist/include/coin/",
     srcs = [
-        "dist/lib/libCoinUtils.so",
+        "dist/lib/libCoinUtils.lib",
     ],
     visibility = ["//visibility:public"],
 )
@@ -101,7 +101,7 @@ cc_library(
     hdrs = glob(["dist/include/coin/Clp*.h*"], exclude_directories = 0),
     strip_include_prefix = "dist/include/coin",
     srcs = [
-        "dist/lib/libClp.so",
+        "dist/lib/libClp.lib",
     ],
     deps = [":coinutils", ":osi"],
     visibility = ["//visibility:public"],

`

Next week i hope to have some time to test actual problems with it. Many thanks for all your help so far.

**Comment by lafar6502** [comment]
BTW the column generating algorithm seems to be a bit better in my testing, but both produce good results. Very nice to have an option to compare. And NESTING_LENGTH seems to work as intended. Great tool and great knowledge you have packed in it.

**Comment by lafar6502** [comment]
@fontanf A question
What happens when there's no solution to the problem, but there exists a partial solution
Situation where not all items can be packed into bins, but some of them can
By default solver doesn't return any solution. But is there an option to force it to return the best incomplete solution found?
(not requesting an implementation here, just curious).

**Comment by fontanf** [comment]
Sorry for late answers, I'm not available right now. Thank you for your feedbacks. I suspect that you get this issue because the problem is infeasible. I didn't test the column generation algorithm with infeasible problems. In these cases, it should be possible to use the knapsack objective instead, but I'm not sure how it behaves currently with multiple bins. I'll give it a look in a few days

**Comment by fontanf** [comment]
> BTW the column generating algorithm seems to be a bit better in my testing, but both produce good results. Very nice to have an option to compare. And NESTING_LENGTH seems to work as intended. Great tool and great knowledge you have packed in it.

Note that there is an option `--vbpp-algorithm` to explicitly select the algorithm for variable-sized bin packing. It can have values `column-generation`, `dichotomic-search` or `sequential-value-correction`.

**Comment by fontanf** [comment]
> @fontanf A question What happens when there's no solution to the problem, but there exists a partial solution Situation where not all items can be packed into bins, but some of them can By default solver doesn't return any solution. But is there an option to force it to return the best incomplete solution found? (not requesting an implementation here, just curious).

There is another objective `knapsack` that maximizes the value of the items packed, while using all the provided bins. Currently, only the direct tree search algorithm is available for knapsack problems. It's also possible to use a column generation algorithm for these problems, and in your case, it may find better solutions. If you provide me a couple of instances, I could try to enable it

**Comment by fontanf** [comment]
Thanks to your previous comments, I've been able to make the compilation with CLP work on Linux and Windows without requiring to install CBC manually. It's pushed on the dev branch. Now this should work out-of-the-box:
```
# Or, to enable the column generation algorithm on Linux:
bazel build --define clp=true -- //...
# Or, to enable the column generation algorithm on Windows:
bazel build --define clp=true --cxxopt=/MT -- //...
```

**Comment by lafar6502** [comment]
@fontanf have some problem with most recent dev compilation on Windows
Looks like 'knitro' is the culprit.My Bazel doesn't like it, but i dont know how to make it happy.
```
D:\devs\packingsolver-dev2>bazel build --define clp=true --cxxopt=/MT -- //...
ERROR: Error computing the main repository mapping: Every .bzl file must have a corresponding package, but '//bazel:knitro.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
```

And BTW, the option
 --vbpp-algorithm sequential-value-correction
is it only working on dev branch builds, or should work on master too? I have master build with clp and it doesn't seem to produce any output

**Comment by fontanf** [comment]
It seems that I forgot to push something. I can't fix it right now. Try to copy this `bazel` directory at the root of your PackingSolver repository https://github.com/fontanf/generalizedassignmentsolver/tree/master/bazel

**Comment by lafar6502** [comment]
Not really urgent, it can wait. 
About the --vbpp-algorithm sequential-value-correction - is this algorithm present in both master and dev?

**Comment by fontanf** [comment]
Yes, it should be

**Comment by fontanf** [comment]
I pushed the missing files. The dev branch should compile.
