### ISSUE TITLE
Rectangle/2d optimization -some questions

### ISSUE THREAD

**Issue by lafar6502** [fontanf/packingsolver#6]
Hi Florian, i'm playing with the 2D / rectangle optimizer.
And have some questions

1. Item orientation - i see the items can have ORIENTED=1/0 and so you can specify if individual item can be rotated during optimization. 
Question: is it possible to control the rotation for groups of items? Like i have a number of items belonging to several groups, for example 3 items from group A, 5 items group B and 2 items group C. Is it possible in any way to control the orientation of a whole group (so either whole group is rotated, or whole group stays in original orientation)? 
- and what is the meaning of --no-item-rotation command line option - disable rotation regardless of ORIENTED setting on items, or something different?
2. GROUP_ID on items - i see there's GROUP_ID field on items. What is the purpose of that? 
3. You can set --objective open-dimension-x(y) and then the solution is not bounded by x (or y) dimension and can go beyond the size of the bin, right? But there's also a --bin-infinite-x(y) command line option. Is there a difference between these two options, and what is the difference?

BTW i'm preparing some prototype optimizer for cutting metal profiles in a manufacturing company. Very promising, i like how the 1d algorithm works. I hope this will become useful in real production, despite all typical problems with quality, mistakes, damages and other unexpected deviations from the plan that can happen in production. Thank you again for this great project, will be thinking about other possible uses of the tool.

**Comment by fontanf** [comment]
Hi,

> Question: is it possible to control the rotation for groups of items? Like i have a number of items belonging to several groups, for example 3 items from group A, 5 items group B and 2 items group C. Is it possible in any way to control the orientation of a whole group (so either whole group is rotated, or whole group stays in original orientation)?

No, its not possible. And I suspect that its a characteristics that would make the algorithms worse if implemented naively. In this case, I would choose the orientation beforehand. For example, choosing the orientation that agrees with the bin dimensions. Or something more sophisticated by solving the problem without the geometric constraints first.

> and what is the meaning of --no-item-rotation command line option - disable rotation regardless of ORIENTED setting on items, or something different?

Yes, exactly.

> GROUP_ID on items - i see there's GROUP_ID field on items. What is the purpose of that?

It's for unloading constraints, when loading a truck. A group is a set of item types that are unloaded at the same time. Groups with smaller id are unloaded first.

> You can set --objective open-dimension-x(y) and then the solution is not bounded by x (or y) dimension and can go beyond the size of the bin, right? But there's also a --bin-infinite-x(y) command line option. Is there a difference between these two options, and what is the difference?

The solver will never pack an item outside of a bin even with the objective `open-dimension-x/y`. If the bin is too small, it won't return any solution with these objectives. The `--bin-infinite-x/y` ensures that there will be a feasible solution.

**Comment by lafar6502** [comment]
Thanks. 
I have looked at --bin-infinite options and it appears that it allows the items to go outside of the bin, either in x or y direction. So i assume this is what you mean - we get some solution, with some items in the bin, but the remaining ones will be outside.
However, this option makes the optimizer lazy - instead of trying to pack more items into the bin it just packs one,  and everything else outside, even if they would fit. At least this is what happened with open-dimension-x objective - it tries to minimize X so it just packed one item to the bin, and everything else outside with X=0 (this way width is minimized). So i assume --bin-infinite is meant for some other algorithm/objective?
btw, BinPackingWithLeftovers - what is it, how does it differ in handling leftovers?

**Comment by fontanf** [comment]
Could you show an example to illustrate this. It's not clear to me if there is a misunderstanding in what does the solver or if there is a bug.

>  btw, BinPackingWithLeftovers - what is it, how does it differ in handling leftovers?

It's only for the last bin of the solution. It minimizes the length of the pattern in this last bin

**Comment by lafar6502** [comment]
OK, here's what i got. Not sure if it's wrong inputs or sth else.

command line: 

`rectangle.exe --verbosity-level 2 --objective open-dimension-x --algorithm auto --bin-infinite-y --items C:\tmpopt\items_a434a432d48b43dfa2194f2fe4e04938.csv --bins C:\tmpopt\bins_a434a432d48b43dfa2194f2fe4e04938.csv -c C:\tmpopt\solution_a434a432d48b43dfa2194f2fe4e04938.csv -t 3`

[Test2D_Simple0.zip](https://github.com/fontanf/packingsolver/files/13453712/Test2D_Simple0.zip)

```
;bins
ID,WIDTH,HEIGHT,COPIES
0,50000,1900,0
1,50000,2500,1

;items
ID,WIDTH,HEIGHT,COPIES,ORIENTED
0,2100,1900,2,1
1,1105,1900,4,0
2,3120,900,1,1
3,720,2100,3,0
4,1720,560,5,0
5,900,2220,1,1

;solution
TYPE,ID,COPIES,BIN,X,Y,LX,LY
BIN,1,1,0,0,0,50000,32040
ITEM,0,1,0,0,0,2100,1900
ITEM,0,1,0,0,1900,2100,1900
ITEM,1,1,0,0,3800,1105,1900
ITEM,1,1,0,0,5700,1105,1900
ITEM,1,1,0,0,7600,1105,1900
ITEM,1,1,0,0,9500,1105,1900
ITEM,3,1,0,0,11400,720,2100
ITEM,3,1,0,0,13500,720,2100
ITEM,3,1,0,0,15600,720,2100
ITEM,4,1,0,0,17700,560,1720
ITEM,4,1,0,0,19420,560,1720
ITEM,4,1,0,0,21140,560,1720
ITEM,4,1,0,0,22860,560,1720
ITEM,4,1,0,0,24580,560,1720
ITEM,5,1,0,0,26300,900,2220
ITEM,2,1,0,0,28520,3120,900
```

**Comment by fontanf** [comment]
Option `--bin-infinite-y` increases the height of the bin. With objective `open-dimension-x`, you certainly rather want to increase the width of the bin. Therefore, you should rather use `--bin-infinite-x`

**Comment by lafar6502** [comment]
thanks, i misunderstood the idea of --bin-infinite
R
