### ISSUE TITLE
Casting issue in rectangle::instance_builder.read_bin_types

### ISSUE THREAD

**Issue by bbeaulant** [fontanf/packingsolver#68]
Hello,

I think that `COST` input value should be cast to `Profit` instead of `Length`.

https://github.com/fontanf/packingsolver/blob/28a845f36fa72a585d7a98a81b84b76f5006deb7/src/rectangle/instance_builder.cpp#L387

Regards

**Comment by fontanf** [comment]
Hi,

Thank you for reporting.

Fixed in 573e7a2adc88b40d775e3e545fac54a4d18616fb
