### ISSUE TITLE
One dimensional - identical cuts are not grouped together (copies = 1 even if the same cut repeats multiple times)

### ISSUE THREAD

**Issue by lafar6502** [fontanf/packingsolver#7]
Hi Florian, an example from my recent experiments

We have 2 bin types

```
ID,X,COST,COPIES
0,3000,3000,3000
1,7000,7000,5000
```

and 2 item types with multiple copies:

```
ID,X,COPIES,NESTING_LENGTH
0,1120,10,-5
1,1770,10,-5
```

And the optimization result gives us identical, repeating cuts:

```
TYPE,ID,COPIES,BIN,X,LX
BIN,0,1,0,0,3000
ITEM,0,1,0,0,1120
ITEM,1,1,0,1125,1770
BIN,0,1,1,0,3000
ITEM,1,1,1,0,1770
ITEM,0,1,1,1775,1120
BIN,0,1,2,0,3000
ITEM,1,1,2,0,1770
ITEM,0,1,2,1775,1120
BIN,0,1,3,0,3000
ITEM,1,1,3,0,1770
ITEM,0,1,3,1775,1120
BIN,0,1,4,0,3000
ITEM,1,1,4,0,1770
ITEM,0,1,4,1775,1120
BIN,0,1,5,0,3000
ITEM,1,1,5,0,1770
ITEM,0,1,5,1775,1120
BIN,0,1,6,0,3000
ITEM,1,1,6,0,1770
ITEM,0,1,6,1775,1120
BIN,0,1,7,0,3000
ITEM,1,1,7,0,1770
ITEM,0,1,7,1775,1120
BIN,0,1,8,0,3000
ITEM,1,1,8,0,1770
ITEM,0,1,8,1775,1120
BIN,0,1,9,0,3000
ITEM,1,1,9,0,1770
ITEM,0,1,9,1775,1120

```

commandline
`main.exe  --verbosity-level 2 --objective variable-sized-bin-packing  --items F0_items.csv --bins F0_bins.csv  -c F0_solution2.csv -t 1`

but shouldn't it return 10 copies of the same cut like below?

```
TYPE,ID,COPIES,BIN,X,LX
BIN,0,10,0,0,3000
ITEM,0,10,0,0,1120
ITEM,1,10,0,1125,1770
```
Also, pls look at this - these two are identical cuts, just the order of cutting is reversed. Shouldn't it be considered same cut?
```
TYPE,ID,COPIES,BIN,X,LX
BIN,0,1,0,0,3000
ITEM,0,1,0,0,1120
ITEM,1,1,0,1125,1770
BIN,0,1,1,0,3000
ITEM,1,1,1,0,1770
ITEM,0,1,1,1775,1120
```

In some cases the number of copies on some cuts is more than 1, but i can't figure out when packingsolver decides to do that instead of making each copy a separate cut.

[F0_bins.csv](https://github.com/fontanf/packingsolver/files/13990355/F0_bins.csv)
[F0_items.csv](https://github.com/fontanf/packingsolver/files/13990356/F0_items.csv)
[F0_solution2.csv](https://github.com/fontanf/packingsolver/files/13990357/F0_solution2.csv)

**Comment by fontanf** [comment]
Hi,

Currently, there is no guarantee that identical or equivalent patterns will be grouped together. That doesn't change the objective value of the solution though.

I agree that it could be a relevant feature. It could be implemented as a post-processing step. I'll think about it

**Comment by lafar6502** [comment]
Yes, you're right, it doesn't change the solution, just made me wonder if there's a secret factor influencing how the results are grouped
And it would be easier to determine if two solutions are identical if they were normalized somehow

**Comment by fontanf** [comment]
It depends on the algorithm used. The dichotomic search and the vbpp to bpp won't group patterns together, while the column generation and the sequential value correction might.

Normalizing might be possible in some simple cases, but not in the general case that the solver handles

But still, it seems easy to check for equivalent/dominated patterns. When adding a pattern to a solution if a pattern already in the solution contains the same items
* if the objective of the new one is better, add the new one and replace each copy of the current one by the new one
* if the objective of the new one is not better, add a copy of the current one

**Comment by lafar6502** [comment]
OK, i have to do some post-processing anyway to use the optimized result, so it might include grouping as well
thanks for clarification

**Comment by lafar6502** [comment]
all clear
