### ISSUE TITLE
Avoid calculating the shape area twice in irregular::InstanceBuilder::read

### ISSUE THREAD

**Issue by bbeaulant** [fontanf/packingsolver#70]
Hello,

In `irregular::InstanceBuilder::read` method, the bin type `cost` can just be set to `-1`. Shape area will be used later in `add_bin_type` method if cost is `-1.`

https://github.com/fontanf/packingsolver/blob/573e7a2adc88b40d775e3e545fac54a4d18616fb/src/irregular/instance_builder.cpp#L268

**Comment by fontanf** [comment]
Hi,

Thank you for reporting.

Fixed in 38c7c94f61c62cbeb069c3c53f5f279844fae313
