### ISSUE TITLE
Bug with 270° allowed angle in irregular problems

### ISSUE THREAD

**Issue by bbeaulant** [fontanf/packingsolver#72]
Hi,

Using a 270° allowed angle generates strange behaviors.

1. With single item input, it throws [this](https://github.com/fontanf/packingsolver/blob/87ce3b563867d62527554af2579d37ad39806073/src/irregular/branching_scheme.cpp#L859) exception
2. And, in the following example, the element rotated 270° overlaps other elements.

<img width="1092" alt="Capture d’écran 2024-08-22 à 08 28 37" src="https://github.com/user-attachments/assets/b08d16f0-caa5-424e-9136-437c049de6bf">

[test_input.json](https://github.com/user-attachments/files/16706400/test_input.json)

Regards

**Comment by fontanf** [comment]
Hi,

Thank you for reporting.

It's an issue with rotations when the solution is built vertically.

Fixed in cd51240887a0c6eacc9bf02ff8678d8bbfdae9a2
