### ISSUE TITLE
EXC_BAD_ACCESS in rectangle problem

### ISSUE THREAD

**Issue by bbeaulant** [fontanf/packingsolver#73]
Hi,

In `NotAnytime` mode, if you set `not_anytime_tree_search_queue_size` parameter to `1` the program crash with an `EXEC_BAD_ACCESS` exception locate here : 

https://github.com/fontanf/packingsolver/blob/87ce3b563867d62527554af2579d37ad39806073/src/rectangle/solution.cpp#L125

Because `solution.bins_` is empty.

Regards

**Comment by fontanf** [comment]
Hi,

Thank you for reporting.

I fixed it a while ago for irregular problems. I forgot to update the code for rectangle problems.

Fixed in 06aca1f5df538e49ca2c7c1574bc759d5ad869aa
