### ISSUE TITLE
Typo in irregulat/solution.cpp

### ISSUE THREAD

**Issue by bbeaulant** [fontanf/packingsolver#95]
https://github.com/fontanf/packingsolver/blob/1f687eb76af343e899853474cec2eed5766de786/include/packingsolver/irregular/solution.hpp#L121

/** Return 'tr**ue**' **if** the solution contains all items. */

**Comment by fontanf** [comment]
Hi,

Thank you for reporting. Fixed in 8cc719184b116bf0f98e179d8696e7c5e4269e18

**Comment by bbeaulant** [comment]
Thanks, but the typo "**iff**" seems to have been missed 😉

**Comment by fontanf** [comment]
"iff" is the standard maths abbreviation for "if and only if".

**Comment by bbeaulant** [comment]
Ok, sorry :)
